In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import sklearn
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

In [2]:
tr = {'x1':[0.346, 0.303, 0.358, 0.602, 0.790, 0.611],
         'x2':[0.780, 0.439, 0.729, 0.863, 0.753, 0.965],
         'y' :[0, 0, 0, 1, 1, 1]}
  
te = {'x1':[0.959, 0.750, 0.395, 0.823, 0.761, 0.844],
         'x2':[0.382, 0.306, 0.760, 0.764, 0.874, 0.435],
         'y' :[0, 0, 0, 1, 1, 1]}
# Create DataFrame
Train = pd.DataFrame(tr)
Test = pd.DataFrame(te)

In [3]:

x_Train=Train.iloc[:,:-1].values
y_Train=Train.iloc[:,-1:].values


x_Test=Test.iloc[:,:-1].values
y_Test=Test.iloc[:,-1:].values 

In [4]:
x_Train

array([[0.346, 0.78 ],
       [0.303, 0.439],
       [0.358, 0.729],
       [0.602, 0.863],
       [0.79 , 0.753],
       [0.611, 0.965]])

In [5]:
y_Train

array([[0],
       [0],
       [0],
       [1],
       [1],
       [1]], dtype=int64)

In [6]:
x_Test

array([[0.959, 0.382],
       [0.75 , 0.306],
       [0.395, 0.76 ],
       [0.823, 0.764],
       [0.761, 0.874],
       [0.844, 0.435]])

In [7]:
y_Test

array([[0],
       [0],
       [0],
       [1],
       [1],
       [1]], dtype=int64)

### 5-a) (3 marks) Implement your own code for a logistic regression classifier, which is trained using gradient descent and cross-entropy error as the error function.

In [8]:
def Sigmoid(result):
    FinalResult = 1/(1+np.exp(-result))
    return FinalResult

In [9]:
def Intialization_of_weight(n_features):
    w = np.zeros((1,n_features))
    b = 0
    return w,b


In [10]:

def Optimization(w, b, X, Y):
    m = X.shape[0]
    
    
    
    FinalResult = Sigmoid(np.dot(w,X.T)+b)
    Y_T = Y.T
    cost = (-1/m)*(np.sum((Y_T*np.log(FinalResult)) + ((1-Y_T)*(np.log(1-FinalResult)))))
   
    
    dw = (1/m)*(np.dot(X.T, (FinalResult-Y.T).T))
    db = (1/m)*(np.sum(FinalResult-Y.T))
    
    gradients = {"dw": dw, "db": db}
    
    return gradients, cost

In [11]:

def Model_Prediction(w, b, X, Y, learning_rate, no_iterations):
    costs = []
    W=[]
    for k in range(no_iterations):
        
        grads, cost = Optimization(w,b,X,Y)
        
        dw = grads["dw"]
        db = grads["db"]
        
        # updating the weights :
        
        w = w - (learning_rate * (dw.T))
        b = b - (learning_rate * db)
        
        if (k % 100 == 0):
            costs.append(cost)
            W.append(w[0][0])
    coefficient = {"w": w, "b": b}
    gradient = {"dw": dw, "db": db}
    
    return coefficient, gradient, costs,W

In [12]:
def Predict(final_Prediction, m):
    y_Prediction = np.zeros((1,m))
    for Z in range(final_Prediction.shape[1]):
        if final_Prediction[0][Z] > 0.5:
            y_Prediction[0][Z] = 1
    return y_Prediction

In [13]:
from sklearn.metrics import accuracy_score



n_features = x_Train.shape[1]

w, b = Intialization_of_weight(n_features)


coefficient, gradient, costs,W = Model_Prediction(w, b, x_Train, y_Train, learning_rate=0.1,no_iterations=400)


w = coefficient["w"]
b = coefficient["b"]

print('Optimized weights', w)
print('Optimized intercept',b)

final_Train_Prediction = Sigmoid(np.dot(w,x_Train.T)+b)
final_Test_Prediction = Sigmoid(np.dot(w,x_Test.T)+b)

m_Train =  x_Train.shape[0]
m_Test =  x_Test.shape[0]

y_Train_Prediction = Predict(final_Train_Prediction, m_Train)
print('Train Accuracy',accuracy_score(y_Train_Prediction.T, y_Train))

y_Test_Prediction = Predict(final_Test_Prediction, m_Test)
print('Test Accuracy',accuracy_score(y_Test_Prediction.T, y_Train))

Optimized weights [[2.16160425 0.71079827]]
Optimized intercept -1.4763538244350112
Train Accuracy 1.0
Test Accuracy 0.6666666666666666


### 5-b)i. (1 mark) What is the logistic model P(ˆy = 1|x1, x2) and its cross-entropy error function?

In [14]:


w=[1.5,0.5]
b=-1
logistic_model = Sigmoid(np.dot(w,x_Train.T)+b)
print("Logistic model-P(ˆy = 1|x1, x2):",logistic_model)

Logistic model-P(ˆy = 1|x1, x2): [0.47726569 0.4192142  0.47539489 0.58285389 0.63679954 0.59844738]


In [15]:


w=[1.5,0.5]
b=-1
m=x_Train.shape[0]
cost = (-1/m)*(np.sum((y_Train*np.log(logistic_model)) + ((1-y_Train)*(np.log(1-logistic_model)))))
print("Logistic model-P(ˆy = 1|x1, x2)-entropy loss:",cost)


Logistic model-P(ˆy = 1|x1, x2)-entropy loss: 4.24695047852859


### 5b) ii. (1 mark) Use gradient descent to update θ0, θ1, θ2 for one iteration. Write down the updated logistic regression model.

In [16]:
w=[1.5,0.5]
b=-1
from sklearn.metrics import accuracy_score



n_features = x_Train.shape[1]


coefficient, gradient, costs,W = Model_Prediction(w, b, x_Train, y_Train, learning_rate=0.1,no_iterations=1)



w = coefficient["w"]
b = coefficient["b"]

print('Optimized weights', w)
print('Optimized intercept',b)

final_Train_Prediction = Sigmoid(np.dot(w,x_Train.T)+b)
final_Test_Prediction = Sigmoid(np.dot(w,x_Test.T)+b)

m_Train =  x_Train.shape[0]
m_Test =  x_Test.shape[0]

y_Train_Prediction = Predict(final_Train_Prediction, m_Train)
print('Train Accuracy',accuracy_score(y_Train_Prediction.T, y_Train))

y_Test_Prediction = Predict(final_Test_Prediction, m_Test)
print('Test Accuracy',accuracy_score(y_Test_Prediction.T, y_Train))

Optimized weights [[1.50535086 0.50196867]]
Optimized intercept -1.0031662597725644
Train Accuracy 1.0
Test Accuracy 0.6666666666666666


### 5-c) iii. (2 mark) At convergence of gradient descent, use the model to make predictions for all the samples in the Test dataset. Calculate and report the accuracy, precision and recall to evaluate this model.

In [17]:
w=[1.5,0.5]
b=-1

from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score



n_features = x_Train.shape[1]




coefficient, gradient, costs,W = Model_Prediction(w, b, x_Train, y_Train, learning_rate=0.1,no_iterations=100000)


w = coefficient["w"]
b = coefficient["b"]

print('Optimized weights', w)
print('Optimized intercept',b)

final_Train_prediciton = Sigmoid(np.dot(w,x_Train.T)+b)
final_Test_Prediction = Sigmoid(np.dot(w,x_Test.T)+b)

m_Train =  x_Train.shape[0]
m_Test =  x_Test.shape[0]

y_Train_Prediction = Predict(final_Train_Prediction, m_Train)
print('Train Accuracy',accuracy_score(y_Train_Prediction.T, y_Train))

y_Test_Prediction = Predict(final_Test_Prediction, m_Test)
print('Test Accuracy',accuracy_score(y_Test_Prediction.T, y_Train))
print('precision',precision_score(y_Test,y_Test_Prediction.T))
print('recall',recall_score(y_Test,y_Test_Prediction.T))



Optimized weights [[31.36347263  7.53262099]]
Optimized intercept -21.190551572578155
Train Accuracy 1.0
Test Accuracy 0.6666666666666666
precision 0.6
recall 1.0
